import org.gradle.internal.os.OperatingSystem;

def javaVersion = 25
def javafxVersion = '25.0.4'
def javafxPlatform = providers.gradleProperty('javafxPlatform').getOrElse(
        OperatingSystem.current().isWindows() ? 'win' : 'linux'
)
def sourceRepositoryDir = file("$rootDir/.gradle/source-repo")

System.setProperty('maven.repo.local', sourceRepositoryDir.absolutePath)

buildscript {
    ext {
        projectGroup = "org.develnext"
        projectVersion = '0.9.3' + (Boolean.getBoolean("release") ? "" : "-SNAPSHOT");
        jphpVersion = "0.9.3-SNAPSHOT"
        wizardVersion = "1.0.0-SNAPSHOT";
    }
}

wrapper {
    gradleVersion = '9.7.1'
}

task installJphpSource(type: Exec) {
    workingDir "$rootDir/3rd-party/jphp"
    commandLine 'cmd', '/c', 'gradlew.bat', 'publishSource'
}

task installWizardSource(type: Exec, dependsOn: installJphpSource) {
    workingDir "$rootDir/3rd-party/wizard-framework"
    commandLine 'cmd', '/c', 'gradlew.bat', 'publishSource'
}

task prepareSourceDependencies(dependsOn: installWizardSource)


allprojects {
    apply plugin: 'idea'
    apply plugin: 'java-library'

    project.group = 'org.develnext'
    project.version = projectVersion

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(javaVersion)
        }
    }

    repositories {
        maven { url = sourceRepositoryDir.toURI() }
        mavenCentral()
    }

    configurations.runtimeClasspath {
        exclude group: 'org.openjfx'
    }

    dependencies {
        compileOnly("org.openjfx:javafx-base:${javafxVersion}:${javafxPlatform}") { transitive = false }
        compileOnly("org.openjfx:javafx-graphics:${javafxVersion}:${javafxPlatform}") { transitive = false }
        compileOnly("org.openjfx:javafx-controls:${javafxVersion}:${javafxPlatform}") { transitive = false }
        compileOnly("org.openjfx:javafx-fxml:${javafxVersion}:${javafxPlatform}") { transitive = false }
        compileOnly("org.openjfx:javafx-media:${javafxVersion}:${javafxPlatform}") { transitive = false }
        compileOnly("org.openjfx:javafx-web:${javafxVersion}:${javafxPlatform}") { transitive = false }
        compileOnly("org.openjfx:javafx-swing:${javafxVersion}:${javafxPlatform}") { transitive = false }
    }

    task sourcesJar(type: Jar, dependsOn: 'classes') {
        archiveClassifier.set('sources')
        from sourceSets.main.allSource
    }

    tasks.withType(JavaCompile) {
        dependsOn rootProject.prepareSourceDependencies
    }
}

configurations {
    javafxRuntime
    launch4jRuntime
    launch4jWorkdir
}

dependencies {
    javafxRuntime("org.openjfx:javafx-base:${javafxVersion}:${javafxPlatform}") { transitive = false }
    javafxRuntime("org.openjfx:javafx-graphics:${javafxVersion}:${javafxPlatform}") { transitive = false }
    javafxRuntime("org.openjfx:javafx-controls:${javafxVersion}:${javafxPlatform}") { transitive = false }
    javafxRuntime("org.openjfx:javafx-fxml:${javafxVersion}:${javafxPlatform}") { transitive = false }
    javafxRuntime("org.openjfx:javafx-media:${javafxVersion}:${javafxPlatform}") { transitive = false }
    javafxRuntime("org.openjfx:javafx-web:${javafxVersion}:${javafxPlatform}") { transitive = false }
    javafxRuntime("org.openjfx:javafx-swing:${javafxVersion}:${javafxPlatform}") { transitive = false }

    launch4jRuntime('net.sf.launch4j:launch4j:3.50') {
        exclude group: 'com.thoughtworks.xstream', module: 'xstream'
    }
    launch4jRuntime 'com.thoughtworks.xstream:xstream:1.4.21'
    launch4jWorkdir('net.sf.launch4j:launch4j:3.50:workdir-win32') { transitive = false }
}

subprojects {
    def dirName = file(it.name).name;
    def bundleDirRoot = "${projectDir}/../../develnext/misc/library/bundles/";
    def bundleDir = "${bundleDirRoot}/${dirName}/";
    def pkgFile = file("$projectDir/package.php.yml")

    if (pkgFile.exists()) {
        task publish(type: Exec) {
            if (OperatingSystem.current().isWindows()) {
                commandLine 'cmd', '/c', 'jppm', 'publish', '-yes'
            } else {
                commandLine 'jppm', 'publish', '-yes'
            }

            workingDir = projectDir
        }

        task hubPublish(type: Exec, dependsOn: 'docBuild') {
            doFirst {
                if (!file(rootDir.path + "/package.hub.yml").isFile()) {
                    throw new GradleException("'package.hub.yml' is not found, please run 'jppm hub:login' in root dir before 'hubPublish'!")
                }

                copy {
                    from rootDir.path + "/package.hub.yml"
                    into projectDir.path
                }
            }

            if (OperatingSystem.current().isWindows()) {
                commandLine 'cmd', '/c', 'jppm', 'hub:publish', '-yes', '-f'
            } else {
                commandLine 'jppm', 'hub:publish', '-yes', '-f'
            }

            workingDir = projectDir
        }

        task docBuild(type: Exec) {
            if (OperatingSystem.current().isWindows()) {
                commandLine 'cmd', '/c', 'jppm', 'doc:build', '-yes'
            } else {
                commandLine 'jppm', 'doc:build', '-yes'
            }

            workingDir = projectDir
        }
    }

    if (it.path.startsWith(":bundles:") || it.name.endsWith("-bundle")) {
        println "-> Detecting bundle '$it.name' ...";

        def resFile = file("$projectDir/.resource")

        if (!resFile.exists()) {
            resFile = file("$projectDir/src/.resource")
        }

        if (resFile.exists()) {
            clean {
                delete bundleDir
            }

            def pr = it;

            jar {
                doLast {
                    copy {
                        from jar.archiveFile.get().asFile
                        from(pr.configurations.runtimeClasspath) {
                            exclude '**/jphp-runtime-*.jar'
                        }

                        into bundleDir
                    }

                    copy {
                        from resFile
                        into "$bundleDir/.."
                        rename ".resource", "${dirName}.resource"
                    }

                    fileTree(bundleDir).visit { FileVisitDetails el ->
                        def name = el.getName()

                        if (name.endsWith(".jar")) {
                            name = name.replaceAll(/(-[0-9]+|\.[0-9]+|-SNAPSHOT)/, "");

                            if (!name.equals(el.getName())) {
                                println "Rename '" + el.file.parent + "/" + name + "' file"

                                def file = file(el.file.parent + "/" + name)

                                if (file.exists()) {
                                    file.delete()
                                }

                                if (!el.file.renameTo(file)) {
                                    el.file.delete()
                                }
                            }
                        }
                    }
                }
            }
        } else {
            println "WARNING, Bundle '$it.name' doesn't have '$projectDir/.resource' file!";
        }
    }

    if (it.path.startsWith(":stubs:")) {
        sourceSets {
            main {
                resources.srcDirs = ['src']
            }
        }
    }
}

project(':jphp-desktop-hotkey-ext') {
    dependencies {
        implementation "org.develnext.jphp:jphp-runtime:$jphpVersion"
        implementation fileTree(dir: 'lib', include: ['*.jar'])
    }
}

project(':dn-app-framework') {
    dependencies {
        implementation "org.develnext.jphp:jphp-core:$jphpVersion"
        implementation "org.develnext.jphp:jphp-gui-ext:$jphpVersion"
    }
}

project(':develnext') {
    apply plugin: 'application'

    startScripts.dependsOn rootProject.prepareSourceDependencies

    dependencies {
        implementation "org.develnext.jphp:jphp-core:$jphpVersion"
        implementation "org.develnext.jphp:jphp-gui-ext:$jphpVersion"
        implementation "org.develnext.jphp:jphp-gui-desktop-ext:$jphpVersion"
        implementation "org.develnext.jphp:jphp-gui-systemtray-ext:$jphpVersion"
        implementation "org.develnext.jphp:jphp-parser-ext:$jphpVersion"

        implementation project(':jphp-gui-tabs-ext')

        implementation project(':develnext-launcher')
        implementation project(':develnext-designer')
        implementation project(':jphp-gui-richtext-ext')
        implementation project(':dn-app-framework')
        implementation project(':develnext-doc')

        // platforms
        file("$rootDir.path/platforms").listFiles().each { file ->
            if (file.directory && file.name.startsWith("develnext-") && file.name.endsWith("-platform")) {
                implementation project(":platforms:$file.name")
            }
        }

        // bundles
        file("$rootDir.path/bundles").listFiles().each { file ->
            if (file.directory && file.name.startsWith("dn-") && file.name.endsWith("-bundle")) {
                compileOnly project(":bundles:$file.name")
            }
        }

        implementation "org.develnext.jphp:jphp-xml-ext:$jphpVersion"
        implementation "org.develnext.jphp:jphp-zip-ext:$jphpVersion"
        implementation "org.develnext.jphp:jphp-json-ext:$jphpVersion"
        implementation "org.develnext.jphp:jphp-yaml-ext:$jphpVersion"
        implementation "org.develnext.jphp:jphp-zend-ext:$jphpVersion"
        implementation "org.develnext.jphp:jphp-sql-ext:$jphpVersion"
        implementation "org.develnext.jphp:jphp-debugger:$jphpVersion"

        implementation "org.develnext.framework:modules/wizard-localization:$wizardVersion"
        runtimeOnly 'org.slf4j:slf4j-simple:1.7.36'

        //compile fileTree(dir: 'libs', include: '*.jar')
    }
}