// Copy this to your bundle directory and rename to build.gradle

apply plugin: 'java'

// Name of bundle
def name = 'dn-my-bundle'

repositories {
    mavenCentral()
    maven { url "https://jitpack.io" }
}

dependencies {
    // maven jar dependencies.
}

// --------------------------------------------------------- //

sourceSets {
    main.resources.srcDirs = ['src']
}

jar {
    exclude '.resource'
}

jar.archiveBaseName.set(name + '.dn')

task bundle(type: Zip, dependsOn: ['clean', 'jar']) {
    println project.buildDir

    from (configurations.runtimeClasspath.allArtifacts.files) {
        into ("bundle/")
    }

    from (configurations.runtimeClasspath) {
        into ("bundle/")
    }

    from ("src/.resource") {
        into ("")
    }

    archiveFileName.set("${name}.dnbundle")
    destinationDirectory.set(project.buildDir)
}

wrapper {
    gradleVersion = '9.7.1'
}
