# MAIN CONFIGURATION

app.name = DevelNext
app.version = 26
app.versionCode = winter
app.versionSnapshot = 0
app.hash = 2026000000
app.uuid =
app.implicitExit = 0

# APP
app.namespace = ide
app.mainForm = MainForm
app.splashForm = SplashForm
app.showMainForm = 1

app.icon = .data/img/DevelNextIco.png

app.fx.splash.autoHide = 1
